### ISSUE TITLE
Methods "touch" and "replace"

### ISSUE THREAD

**Issue by ARTPROITCo** [e-oz/Memory#9]
Hi, Jamm
Implementation of methods "touch" and "replace" will be?

**Comment by jamm** [comment]
@ARTPROITCo I can't find documentation about these commands (http://redis.io/commands#list). 
As a workaround, you can call method as magic: `$RedisServer->touch(arguments)` and command `touch` with arguments will be sent to Redis.
If you can give links to documentation of new commands, I'll add their signatures.

**Comment by e-oz** [comment]
there are no such methods in Redis API
